config/routes.rb
Rails.application.routes.draw do
 
  
 
  root to: 'pages#home'
  get '/bonjour(/:name)',to:'pages#salut', as: 'salut'
  resources :posts
  resources :categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord 


    validate :ma_super_method_de_validation
    before_validation :default_slug
    #Ex:- :default =>''


def as_json(options = nil)
    super(only: [:name, :id, :created_at])
end

def ma_super_method_de_validation
    if name.length != 2
        errors.add(:name,'le champs droit etre de deux caractere')
    end

end
private

def default_slug 
    if !self.name.empty? && self.slug.empty?
    self.slug = name.parameterize
end
end
end

app/models/validator/name_validator.rb
 class NameValidator < ActiveModel::Validator
  
    def validate(record)
        if record.name.nil? || record.name.length != 20
record.errors.add(:name, :not_2,{ message: 'le champs droit etre de 20 caractere'})
        end
        if record.content.nil? || record.content.length != 50
            record.errors.add(:content, 'le champs droit etre de 50 caractere')
        end




    end 

    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index
    @session = session[:user_id] = { isername:'Jaures', id: 3}
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def update

    @category = Category.find(params[:id])

    @category.update(category.params)
    
    redrect_to category_path(@category.id)

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to category_path(@category.id)
  end

  def edit
    @category = Category.find(params[:id])

  end
  
  private

  def category_params 
    params.require(:category).permit(:name,:slug)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def salut

        @name =  params[:name]
    
    end
    def home

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  before_action :set_post, only: [:update, :edit, :show, :destroy]


  def index
    session[:user_id] = 4
    @posts = Post.all

    respond_to do |format|
      format.html 
      format.json {render json: @posts}

    
    end
  end


   def show 

   respond_to do |format|
      format.html 
      format.json {render json: @post}
   end 

   end

   def edit 
    
   end

  

   def update 
  
   flash[:notice] = "Article modifier avec success"

   
   if  @post.update(post_params)
    redirect_to posts_path
   else 
    render 'edit'
   end

  end

  def new 
    @post = Post.new
  end

  

  def  create
    flash[:notice] = "Article Cree avec success"
    post = Post.create(post_params)
    redirect_to post_path(post.id) 
  end

  def destroy
    flash[:notice] = "Article Supprimer  avec success"
    @post.destroy
    redirect_to post_path 
  end



  private

  def post_params 
    params.require(:post).permit(:name,:content, :slug)
  end

  def set_post
    @post = Post.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Editer la categories</h1>




<%= form_for @category do |f| %>
   <div class="from-group">
<%= f.text_field :name, placeholder:'Nom', class: 'form-control' %> 
</div>
<div class="from-group">
<%= f.text_field :slug, placeholder:'url', class: 'form-control' %> 
</div>
<div class="from-group">
    <button class="btn btn-primary" type="submit">Modifier la Categorie</button>
</div>

<% end %>

app/views/categories/index.html.erb
<h1>Les Categories</h1>

<p>
    Session : <%= @session.inspect %>
</p>
<table class="table table-striped">
<thead>
<tr>
    <td>ID</td>
    <td>Nom</td>
    <td>Action</td>
</tr>


</thead>
<tbody>
    <% @categories.each do |category| %>
    <tr>
        <td><%= category.id%></td>
        <td><%= category.name%></td>
        <td>
            <a href="<%= edit_category_path(category.id)%>" class="btn btn-primary ">Edité</a>
            <a href="<%= category_path(category.id)%>" class="btn btn-danger" data-confirm="sur ?" data-method="delete">Supprimer</a>

        </td>
    </tr>
    <% end %>
</tbody>
</table>


<p>
    <a href="<%= new_category_path %>" class="btn btn-success btn-xs">Cree une nouvelle categorie</a>
</p>

app/views/categories/new.html.erb
<h1>Nouvelle Categories</h1>


<%= form_for @category do |f| %>
   <div class="from-group">
<%= f.text_field :name, placeholder:'Nom', class: 'form-control' %> 
</div>
<div class="from-group">
<%= f.text_field :slug, placeholder:'url', class: 'form-control' %> 
</div>
<div class="from-group">
    <button class="btn btn-primary" type="submit">Creer la Categorie</button>
</div>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jaures|Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4" href="<%= root_path %>">Application |Blog</span>
    </a>
<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <ul class="nav nav-pills">
     
      <li class="nav-link"><a href="<%= posts_path %>">Articles</a></li>
      <li class="nav-link"><a href="<%= categories_path %>">Catègories</a></li>
    </ul>
  </header>
</div>
</nav>

  <body>
  
  </header>
</div>



    
    <div class="container " style="padding-top: 5rem;">
      <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice]%></div>
    
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bienvenue Sur le site </h1>


<p>lorem ipsum dolor sit amet, consectet loremet tincidunt</p>

app/views/pages/salut.html.erb
salut <%= @name %>  comment tu vas ??

app/views/posts/edit.html.erb
<h1> Editer Article </h1>


<% if @post.invalid? %>
<div class="alert alert-danger">


<ul>

<% @post.errors.full_messages.each do |message| %>

<li><%= message %></li>


<% end %>
</ul>

</div>

<% end %>









<%= form_for @post do |f| %>
    <div class="form-group">
    <label>Titre de article </label>
    <%= f.text_field :name, class:'form-control' %>
    </div>


    <div class="form-group">
        <label>URL de l'article </label>
        <%= f.text_field :slug, class:'form-control' %>
        </div>



    <div class="form-group">
        <label>Contenue de l'article </label>
        <%= f.text_area :content, class:'form-control' %>
        </div>



        <div class="form-group">
            <button type="submit" class="btn btn-primary">Modifier l'article</button>
        </div>
        
    <% end %>

app/views/posts/index.html.erb
<h1>Articles</h1>



<% @posts.each do |post| %>

        <h2> <%= post.name %></h2>
        <p>  <%= post.content %></p>
        <p>
            <a href="<%= post_path(post.id)  %>" class="btn btn-primary">Lire La Suite</a>
            <a href="<%= edit_post_path(post.id)  %>" class="btn btn-bleu">Editer</a>
            <a href="<%= post_path(post.id)%>" class="btn btn-danger" data-confirm="sur ?" data-method="delete">Supprimer</a>
        </p>

<% end %>

<p>

<a href="<%= new_post_path %>" class="btn btn-success">Cree Un article</a> 
</p>

app/views/posts/new.html.erb
<h1> Créer Un article </h1>

<%= form_for @post do |f| %>
    <div class="form-group">
    <label>Titre de article </label>

    
    <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
        <label>Contenue de l'article </label>
    
        
        <%= f.text_area :content, class:'form-control' %>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Créer l'article</button>
        </div>
        
    <% end %>

app/views/posts/show.html.erb
<h1><% @post.name %></h1>


<p><%= @post.content%></p>



<p>
    
    <a href="<%= posts_path %>" class="btn btn-primary">Revenir aux articles</a>
    </p>